language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - nightly

branches:
  only:
    - master

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("NLSProblems"); Pkg.test("NLSProblems"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("NLSProblems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
